#!/bin/sh
set -eu

if [ -n "${DEB_HOST_GNU_TYPE:-}" ]; then
    CROSS_COMPILE="$DEB_HOST_GNU_TYPE-"
else
    CROSS_COMPILE=
fi

cd "$AUTOPKGTEST_TMP"

cat <<EOF > handytest.c
#include <gtk/gtk.h>
#include <handy.h>

int
main (int    argc,
      char **argv)
{
	gtk_init(&argc, &argv);
	hdy_init();
	hdy_keypad_new(FALSE, TRUE);
}
EOF

${CROSS_COMPILE}gcc -o handytest handytest.c $(${CROSS_COMPILE}pkg-config --cflags --libs libhandy-1)
echo "build ok"
[ -x handytest ]
xvfb-run -a -s "-screen 0 1024x768x24" ./handytest
echo "starts ok"
