#!/usr/bin/python3
#
# Make sure gobject introspection works

import gi

gi.require_version('Handy', '1')
from gi.repository import Handy

group = Handy.SwipeGroup()

assert type(group).__name__ == 'SwipeGroup'
assert group.get_swipeables() == []
